services:
  db:
    image: postgres:16-alpine
    container_name: mundial-db
    environment:
      POSTGRES_USER: mundial
      POSTGRES_PASSWORD: mundial_secret_2026
      POSTGRES_DB: mundialapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mundial-redis
    ports:
      - "6379:6379"

volumes:
  db_data: